server: 
  port: 8761
  
eureka: 
  instance: 
    hostname: 172.16.79.23
  client: 
    registerWithEureka: false
    fetchRegistery: false
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server: 
    renewalPercentThreshold=0.49